---
- hosts: ansible
  become: yes
  vars:
    docker_image_name: "myapp"
    docker_image_tag: "v1.0"
    docker_registry: "docker.io"
    docker_username: "advit2012"
    docker_password: "{{ docker_password | default('Manjeet123') }}"  # Secure this using Ansible Vault or Jenkins credentials
    build_path: "{{ ansible_env.HOME }}"  # Adjust this path as needed
    docker_file_path: "Dockerfile"  # Adjust if Dockerfile is in a different location

  tasks:
    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Build the Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: build
        build:
          path: "{{ build_path }}"  # Path to the directory containing Dockerfile
          dockerfile: "{{ docker_file_path }}"  # Path to Dockerfile within build path

    - name: Log in to Docker registry
      docker_login:
        registry: "{{ docker_registry }}"
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Push the Docker image to the registry
      docker_image:
        name: "{{ docker_registry }}/{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        push: yes

    - name: Log out from Docker registry
      docker_login:
        registry: "{{ docker_registry }}"
        state: absent
