---
- hosts: all
  become: yes
  tasks:

    - name: Install Docker
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installDocker.sh -P /tmp
        chmod 755 /tmp/installDocker.sh
        bash /tmp/installDocker.sh
        systemctl restart docker.service

    - name: Install CRI-Docker
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installCRIDockerd.sh -P /tmp
        chmod 755 /tmp/installCRIDockerd.sh
        bash /tmp/installCRIDockerd.sh
        systemctl restart cri-docker.service

    - name: Install Kubernetes
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installK8S.sh -P /tmp
        chmod 755 /tmp/installK8S.sh
        bash /tmp/installK8S.sh

    - name: Initialize Kubernetes Master Node
      shell: |
        kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock --ignore-preflight-errors=all
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      register: kubeadm_init

    - name: Install Calico Networking Driver
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml

    - name: Save kubeadm join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Save join command to file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /tmp/kubeadm-join.sh
        mode: '0755'
