---
- hosts: ansible
  become: yes
  tasks:
    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
        
    
