- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install maven
    command : apt insatll maven -y
    become : yes
    become_user : root

 

