apiVersion: apps/v1
kind: Deployment
metadata:
  name: advit
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: advit2012/healthcare13aug:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s
spec:
  selector:
    app: spring
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: NodePort
